### ISSUE TITLE
Preliminary examination

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/icc-beta#49] opened 2014-09-22 11:48 UTC
A cut down version of the situation layout:

![05-03-stage-preliminary-examination](https://cloud.githubusercontent.com/assets/1565953/4355588/423fd4d8-424e-11e4-87ae-5e7f60e4bbb3.jpg)

**Comment by simmigaba** [comment] 2015-01-05 08:20
Hi Armin - In existing website, for each Preliminary Examination we display any latest Press Release, Report or Statement under one common section and heading of "Relevant documents, reports and statements". All these types have same Press Release Content Type. But in existing site, the data is fragmented across several subsites, central libraries due to historic migrations and change in approach over the period of time. For new website, I just want to confirm that do you visualize one centralized library for Press Releases, Reports and Statements or 2 i.e. one for Press Release and other for Reports and Statements? And as decided earlier based on "Related To" field we will display appropriate content on specific PE page. And is there any value addition to display Press Releases under separate heading and Reports/ Statements under separate headings on PE page or should we leave them under one common heading as it is at the moment? Please clarify.

Rob - Please add anything from your side. As you suggested during alpha phase, apart from Press Release/ Report and Statements, we will also display links to specific sections of Annual Report on PE (HTML Report).

**Comment by robertocarroll** [comment] 2015-01-05 10:07
When you put it like that, it seems odd that "press releases" should be included along with documents and reports. 

Will there be any press releases for preliminary examinations? Or are there only "statements", i.e. "press releases" from the OTP?

For me, it really comes down to the frequency - if there's going to be a lot of a particular type then they need a separate section so as not to drown out the other important documents, such as annual report. Hope that helps.

**Comment by simmigaba** [comment] 2015-01-05 10:20
To give more clarity, if you see Colombia:
http://www.icc-cpi.int/en_menus/icc/structure%20of%20the%20court/office%20of%20the%20prosecutor/comm%20and%20ref/pe-ongoing/colombia/Pages/colombia.aspx

then "ICC Office of the Prosecutor concludes visit to Colombia" is a Press Release and "Situation in Colombia - Interim Report" is a Report.

Same way for Georgia, 
http://www.icc-cpi.int/en_menus/icc/structure%20of%20the%20court/office%20of%20the%20prosecutor/comm%20and%20ref/pe-ongoing/georgia/Pages/georgia.aspx

"Georgia preliminary examination: OTP concludes second visit to the Russian Federation" 
and "No impunity for crimes committed in Georgia: OTP concludes second visit to Georgia in context of preliminary examination" 
are Press Releases whereas "Prosecutor's statement on Georgia" is a Statement.

So if you notice different PEs have different kind of documents i.e. 3 Types -- Statement, Report and Press Release. And currently all these are shown together in one section without any differentiation. Though we can include the "Type" value along with Publishing date in the list if its of any value to end user to know whether its Press Release, Statement or Report.

In the existing site, Links to Annual OTP Report is not shown as list but in the PE introductory Text itself. As per your suggestion you also want to include these as items in list which will point to specific section in Annual OTP report. So these links will always be first to display in the list followed by any Press Release, Statement or Report related to PE.

**Comment by taslaman** [comment] 2015-01-12 09:38
Dear Simmi and Rob,

We can merge press releases, statements and reports in one SP library, as we can always display data by the document type, so this would not be a problem. We do have a lot of PDF files of the reports with no metadata on the website. The problem is not so much in entering the metadata, but in binding the different language versions of documents. It would be great to use a display template page to show all of these PDFs. If we cannot achieve this, we can use the current system of creating a HTML page to feature the links to the reports. 

Kind regards,
armin.

**Comment by simmigaba** [comment] 2015-01-12 09:57
Hi Armin - Thanks for your response. Can you please elaborate what do you mean by:
-- It would be great to use a display template page to show all of these PDFs.-- 

In context to above WebPart for "Documents Reports and Statements", this WebPart will fetch latest Press Release, Report or Statements from the Centralized document library filtered by "Related To" which will be Preliminary Examination value i.e. Georgia in this case. All the existing PR, Statement and Reports should be migrated to this centralized library as part of content migration project.
In above Webpart,  Title links can point to a PDF report, ASP Page, HTML Page etc whatever it is depending upon type of document uploaded or Page created using a Template by the content Administrators. 
As part of current beta dev phase, we are not creating any new Page Template and library data structure and idea is to re-use the existing Press Release Template that is currently used to create ASP Pages for PR, Reports and Statements. Though you can always change the Template as require. But in context to this issue, we will just create a WebPart that will fetch latest PR, Reports and Statements with link to document / Page uploaded/ created in the document library.

Please let me know if I am missing something.

**Comment by taslaman** [comment] 2015-01-12 11:08
Hi Simmi, We are currently using pages to carry the links to the PDF files. I would like to move away from that practice, but I don't really know how to do this without making bigger changes. 

The reports are the problem, as they usually exist in PDF format. What I would recommend is to leave all the previous ones in the state they are now, and build a system where we would upload a PDF file to the SP library, approve it and the web part would do the rest. we can do this part now, but the difficulty comes with the multiple language versions of a report, as some might have Spanish, Arabic, Russian and/or other versions. How would we deal with that? We can find a binding factor for them with ease, but displaying them would be a problem. 

We can then either create a new logic for them, or carry on with the current system, where pages contain the links to the files, but also the metadata for them as well. How would this be manifested in the search engine?

Also, if we create a new logic for the PDF files, I would then slowly move all the old reports to the new system as well. I would take time after the launch to do that.

**Comment by simmigaba** [comment] 2015-01-16 12:38
Several Changes are done for PE Page as below:
-- All the Press Release, Statements and Reports related to PE are fetched from centralized document library filtered based on Related To Field
-- Applied Latest CSS styling
-- Document Type for each record is displayed to give more clarity.

Please see detailed implementation info in below snapshot. Please comment if any other changes has to be done for PE page.

![image](https://cloud.githubusercontent.com/assets/5706403/5776227/828e1fd8-9daa-11e4-8329-658fc3594219.png)

**Closed as completed by simmigaba** 2015-01-16 12:38 UTC
Labels: Design, Dev, 02-Situation, Templates, 05-Stage
